from os.path import join

class Data(Data):
	VersionPath = join(Data.MC, 'versions', Data.Version)
	CLASSPATH   = [
		"gson-2.10.jar",
		"fastutil-8.5.9.jar",
		"failureaccess-1.0.1.jar",
		"datafixerupper-6.0.8.jar",
		"commons-logging-1.2.jar",
		"commons-lang3-3.12.0.jar",
		"commons-io-2.11.0.jar",
		"commons-compress-1.21.jar",
		"commons-codec-1.15.jar",
		"brigadier-1.1.8.jar",
		"blocklist-1.0.10.jar",
		"authlib-4.0.43.jar",
		"text2speech-1.17.9.jar",
		"slf4j-api-2.0.1.jar",
		"patchy-2.2.10.jar",
		"oshi-core-6.2.2.jar",
		"netty-transport-native-unix-common-4.1.82.Final.jar",
		"netty-transport-native-epoll-4.1.82.Final-linux-x86_64.jar",
		"netty-transport-native-epoll-4.1.82.Final-linux-aarch_64.jar",
		"netty-transport-classes-epoll-4.1.82.Final.jar",
		"netty-transport-4.1.82.Final.jar",
		"netty-resolver-4.1.82.Final.jar",
		"netty-handler-4.1.82.Final.jar",
		"netty-common-4.1.82.Final.jar",
		"netty-codec-4.1.82.Final.jar",
		"netty-buffer-4.1.82.Final.jar",
		"lwjgl-tinyfd-3.3.1-natives-windows-x86.jar",
		"lwjgl-tinyfd-3.3.1-natives-windows-arm64.jar",
		"lwjgl-tinyfd-3.3.1-natives-windows.jar",
		"lwjgl-tinyfd-3.3.1-natives-macos-arm64.jar",
		"lwjgl-tinyfd-3.3.1-natives-macos.jar",
		"lwjgl-tinyfd-3.3.1-natives-linux.jar",
		"lwjgl-tinyfd-3.3.1.jar",
		"lwjgl-stb-3.3.1-natives-windows-x86.jar",
		"lwjgl-stb-3.3.1-natives-windows-arm64.jar",
		"lwjgl-stb-3.3.1-natives-windows.jar",
		"lwjgl-stb-3.3.1-natives-macos-arm64.jar",
		"lwjgl-stb-3.3.1-natives-macos.jar",
		"lwjgl-stb-3.3.1-natives-linux.jar",
		"lwjgl-stb-3.3.1.jar",
		"lwjgl-opengl-3.3.1-natives-windows-x86.jar",
		"lwjgl-opengl-3.3.1-natives-windows-arm64.jar",
		"lwjgl-opengl-3.3.1-natives-windows.jar",
		"lwjgl-opengl-3.3.1-natives-macos-arm64.jar",
		"lwjgl-opengl-3.3.1-natives-macos.jar",
		"lwjgl-opengl-3.3.1-natives-linux.jar",
		"lwjgl-opengl-3.3.1.jar",
		"lwjgl-openal-3.3.1-natives-windows-x86.jar",
		"lwjgl-openal-3.3.1-natives-windows-arm64.jar",
		"lwjgl-openal-3.3.1-natives-windows.jar",
		"lwjgl-openal-3.3.1-natives-macos-arm64.jar",
		"lwjgl-openal-3.3.1-natives-macos.jar",
		"lwjgl-openal-3.3.1-natives-linux.jar",
		"lwjgl-openal-3.3.1.jar",
		"lwjgl-jemalloc-3.3.1-natives-windows-x86.jar",
		"lwjgl-jemalloc-3.3.1-natives-windows-arm64.jar",
		"lwjgl-jemalloc-3.3.1-natives-windows.jar",
		"lwjgl-jemalloc-3.3.1-natives-macos-arm64.jar",
		"lwjgl-jemalloc-3.3.1-natives-macos.jar",
		"lwjgl-jemalloc-3.3.1-natives-linux.jar",
		"lwjgl-jemalloc-3.3.1.jar",
		"lwjgl-glfw-3.3.1-natives-windows-x86.jar",
		"lwjgl-glfw-3.3.1-natives-windows-arm64.jar",
		"lwjgl-glfw-3.3.1-natives-windows.jar",
		"lwjgl-glfw-3.3.1-natives-macos-arm64.jar",
		"lwjgl-glfw-3.3.1-natives-macos.jar",
		"lwjgl-glfw-3.3.1-natives-linux.jar",
		"lwjgl-glfw-3.3.1.jar",
		"lwjgl-3.3.1-natives-windows-x86.jar",
		"lwjgl-3.3.1-natives-windows-arm64.jar",
		"lwjgl-3.3.1-natives-windows.jar",
		"lwjgl-3.3.1-natives-macos-arm64.jar",
		"lwjgl-3.3.1-natives-macos.jar",
		"lwjgl-3.3.1-natives-linux.jar",
		"lwjgl-3.3.1.jar",
		"logging-1.1.1.jar",
		"log4j-slf4j2-impl-2.19.0.jar",
		"log4j-core-2.19.0.jar",
		"log4j-api-2.19.0.jar",
		"jopt-simple-5.0.4.jar",
		"joml-1.10.5.jar",
		"jna-platform-5.12.1.jar",
		"jna-5.12.1.jar",
		"java-objc-bridge-1.1.jar",
		"icu4j-71.1.jar",
		"httpcore-4.4.15.jar",
		"httpclient-4.5.13.jar",
		"guava-31.1-jre.jar"
	]
	CLASSPATH   = [join('{Data.Lib}', path) for path in CLASSPATH]
	Natives     = join(VersionPath, 'natives')
	AssetsIndex = '1.20'

	CLASSPATH.append(join(VersionPath, Data.Version + ".py"))
del Data.Flags.JVM[-3] # Deshabilitar parametro natives.